export const FETCH_DATA="FETCH_DATA"
export const LOGIN_SUCCESS = "USERS_LOGIN_SUCCESS";
export const FETCH_ORDER_SUMMARY = "FETCH_ORDER_SUMMARY";
export const LIST_OF_PRODUCTS = "LIST_OF_PRODUCTS";
export const LIST_OF_ORDERS = "LIST_OF_ORDERS";
